dist: trusty
language: c

before_script:
  - ./shellbuild/ubuntu/14.04/init.sh

script:
  - ./compile.sh

notifications:
  email: false

git:
  depth: false

addons:
  sonarcloud:
    organizations: "jasonyangshadow-github"
script:
  - sonar-scanner
